In [124]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [125]:
train = pd.read_csv("/kaggle/input/competitions/binary-classification-with-bank-churn-dataset/train.csv")
test = pd.read_csv("/kaggle/input/competitions/binary-classification-with-bank-churn-dataset/test.csv")

In [126]:
train.head()

,id,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,0,15672899.0,Fanucci,651.0,France,Female,33.0,0.0,0.00,2.0,1.0,1.0,94499.06,0.0
1,1,15572374.0,Pinto,639.0,Spain,Female,42.0,9.0,0.00,2.0,0.0,0.0,152874.75,0.0
2,2,15715888.0,Uspenskaya,619.0,Spain,Male,34.0,5.0,0.00,2.0,1.0,1.0,79919.13,0.0
3,3,15651740.0,Chukwukadibia,543.0,France,Male,33.0,7.0,0.00,2.0,0.0,0.0,16929.41,0.0
4,4,15604551.0,Iadanza,749.0,France,Female,37.0,4.0,101470.29,1.0,1.0,1.0,121098.65,0.0

In [127]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               15000 non-null  int64
 1   CustomerId       15000 non-null  float64
 2   Surname          15000 non-null  object
 3   CreditScore      15000 non-null  float64
 4   Geography        15000 non-null  object
 5   Gender           15000 non-null  object
 6   Age              15000 non-null  float64
 7   Tenure           15000 non-null  float64
 8   Balance          15000 non-null  float64
 9   NumOfProducts    15000 non-null  float64
 10  HasCrCard        15000 non-null  float64
 11  IsActiveMember   15000 non-null  float64
 12  EstimatedSalary  15000 non-null  float64
 13  Exited           15000 non-null  float64
dtypes: float64(10), int64(1), object(3)
memory usage: 1.6+ MB

In [128]:
X=train.drop(columns=["Exited"])
y=train["Exited"]

In [129]:
X.describe().T

,count,mean,std,min,25%,50%,75%,max
id,15000.0,7.499500e+03,4.330271e+03,0.00,3749.75,7499.50,11249.25,1.499900e+04
CustomerId,15000.0,1.571124e+07,1.626541e+06,15565796.00,15634291.50,15690169.00,15757541.00,1.569181e+08
CreditScore,15000.0,6.583421e+02,7.250106e+01,431.00,602.00,661.00,709.00,8.500000e+02
Age,15000.0,3.772580e+01,8.192152e+00,18.00,32.00,37.00,42.00,7.400000e+01
Tenure,15000.0,5.049867e+00,2.803338e+00,0.00,3.00,5.00,7.00,1.000000e+01
Balance,15000.0,4.311646e+04,6.005080e+04,0.00,0.00,0.00,111099.79,1.879115e+05
NumOfProducts,15000.0,1.588667e+00,5.299279e-01,1.00,1.00,2.00,2.00,4.000000e+00
HasCrCard,15000.0,7.779333e-01,4.156496e-01,0.00,1.00,1.00,1.00,1.000000e+00
IsActiveMember,15000.0,4.882000e-01,4.998774e-01,0.00,0.00,0.00,1.00,1.000000e+00
EstimatedSalary,15000.0,1.178245e+05,6.655244e+04,11.58,82817.37,122488.59,156778.04,5.664540e+06

In [130]:
for col in X.columns:
    print(col,": ",X[col].unique())
    print("\n")

id :  [    0     1     2 ... 14997 14998 14999]


CustomerId :  [15672899. 15572374. 15715888. ... 15658158. 15573769. 15589715.]


Surname :  ['Fanucci' 'Pinto' 'Uspenskaya' 'Chukwukadibia' 'Iadanza' 'Chigozie'
 'Teng' 'Lo Duca' 'Nwachinemelu' 'Chiganu' 'Chikwado' 'H?' 'Onwudiwe' 'Y?'
 'Nnachetam' 'Olisaemeka' 'Zetticci' 'Dickson' "P'eng" 'Chukwuemeka'
 'Chien' "Ch'eng" 'Palerma' 'Genovese' 'Rizzo' 'Kao' 'Hargraves'
 'Chukwudi' 'Onyemere' 'Moore' 'Pagnotto' 'Hsia' 'Chidiebele' 'Y?an'
 'Onyekaozulu' 'Eames' 'Smith' "Ch'ang" 'Chiu' 'Fiorentino' 'Uwakwe'
 'Hsing' 'Yevseyev' "Ch'iu" 'Ting' 'Lo' 'Onuchukwu' 'Beyer' 'Calabrese'
 'Yobachi' 'Dilibe' 'McGregor' 'Ifeajuna' 'Ugonnatubelum' "Ch'ien" 'Tuan'
 'Brient' "Ts'ao" "T'ao" 'Onyekachi' 'Nwankwo' 'Hsu' 'Loyau' 'Milani'
 'Chia' 'Hs?eh' 'DeRose' 'Bazarova' 'Yeh' 'Nwokezuike' 'Hoolan' "T'ien"
 'Okwuoma' 'Yuan' 'Hsieh' 'Sievier' 'Maclean' 'Galkina' 'L?' 'Sagese'
 'Onyeoruru' 'Chidozie' 'Lucchese' 'Chibugo' 'Chinedum' 'Niu'
 'Chukwuebuka' "Ch'en" 'Obialo' 'Hsueh' "Ts'ui" 'Onwuamaeze' 'Macdonald'
 'Ku' 'Pisano' 'Chukwumaobim' 'Macleod' 'Iloerika' 'Chukwualuka' 'Dancy'
 'Brown' 'White' "O'Brien" 'Iweobiegbunam' 'Nwabugwu' 'Shao' "Ch'in"
 'Chizoba' 'Baryshnikov' 'Nworie' 'Fomin' 'Hao' 'Hs?' 'Chinwenma' 'Ozioma'
 'Whitehead' 'Tsao' 'Onwumelu' 'Hsiung' 'Tien' 'Chukwufumnanya' 'Pirozzi'
 'Kuo' 'Istomin' 'Nwachukwu' "K'ung" 'Aksenov' 'Onyinyechukwuka'
 'Lucchesi' 'Ebelechukwu' 'Nnaife' 'Bancks' 'Biryukova' 'Kerr' 'Crawford'
 "O'Sullivan" 'Nnonso' 'Cone' 'Lettiere' 'Trevisano' 'Clements' 'Ozoemena'
 'McIntyre' 'Horsley' 'Bibi' 'Cremonesi' 'Tung' 'Yuryeva' 'Chiedozie'
 "Ts'ai" 'Ijendu' 'Ndubueze' 'Onuoha' 'Chigolum' 'Efremov' 'Frolov'
 "O'Donnell" 'Chidiegwu' 'Nnamutaezinwa' 'Milano' 'Lu' 'Shih' 'Aitken'
 'Ewing' 'Mazzanti' 'Chigbogu' 'Chukwujamuike' 'Chiekwugo' 'Udegbunam'
 'Okwuadigbo' 'Chikwendu' 'Chidumaga' 'Chukwukere' 'Yermakova' 'Chijindum'
 'Chiang' 'Achebe' 'Manna' 'Nwoye' "T'ang" 'Nkemdirim' 'Chidi' 'Chiemenam'
 'Chienezie' 'Cameron' 'Gaffney' 'Chinweuba' 'Chu' 'Pugh' 'Chidubem'
 'Trevisani' 'Su' 'Chukwubuikem' 'Uspensky' 'Nkemjika' 'Nkemdilim' 'Mazzi'
 'Walker' 'Yermakov' 'Okwudilichukwu' 'Chinomso' 'Chidimma' 'Bogle'
 'Tretiakova' 'Ritchie' 'Lai' 'Onyemauchechukwu' 'Chidiebere' 'Tseng'
 'Mancini' 'Udegbulam' 'Yefimova' 'Baresi' 'Johnson' 'Yuriev' 'Fancher'
 'Onio' 'Cattaneo' 'Chuang' 'Okagbue' 'Hsiao' 'Bellasis' 'Napolitani'
 'Palermo' 'Mackey' 'Gordon' 'Ndubuagha' 'Goliwe' 'Grieve' 'Toscani'
 'Ugochukwu' 'Ugochukwutubelum' 'Bufkin' 'Burt' 'Meng' 'Onyekachukwu'
 'Lucciano' 'Chukwujekwu' 'Chukwuhaenye' 'Okechukwu' 'Dyer' 'Chibueze'
 'Yobachukwu' 'K?' 'Milanesi' 'Folliero' 'Hargreaves' 'Ukaegbulam'
 'Bischof' 'Garmon' 'Chin' 'Kambinachi' 'Tsou' 'Liao' 'Watson' 'Flemming'
 'Tsai' 'Nwora' 'Chinagorom' 'Thompson' 'Kosisochukwu' 'Udokamma' 'Obiora'
 'Chioke' 'Martin' 'Kisch' 'Milne' 'Piazza' 'Yancy' 'Zikoranachidimma'
 'Yefremov' 'Rolon' 'Mironova' 'Gebhart' 'Ogochukwu' 'Shubin' 'Oguejiofor'
 'Calabresi' 'Muecke' 'Fan' 'Yermolayev' 'Horsfall' 'Pisani' 'Sun'
 'Shubina' 'Onuora' "P'an" 'Eluemuno' 'Nebechukwu' 'Chialuka' 'Wilson'
 'Fenton' 'Ebelegbulam' 'Ojiofor' 'Gant' 'Mbanefo' 'Nwokike' 'Aksyonova'
 'Iheatu' 'Ko' 'Chiazagomekpele' 'Chiawuotu' 'Chiazagomekpere' 'Ainsworth'
 'Obidimkpa' 'Scott' "T'an" 'Binder' 'Naylor' 'Dennys' 'Davison'
 'Chinweike' 'Ozerova' 'Yermolayeva' 'Ginn' 'Uvarova' 'Onyeorulu'
 'Ulyanova' 'Obiajulu' 'Young' 'Onyemauchechi' 'Estep' 'De Salis'
 'Dufresne' 'Onyemachukwu' 'Koger' 'Chizuoke' 'Nock' 'Sells' 'Surname'
 'Chinonyelum' 'Fiorentini' 'Uwaezuoke' 'Gboliwe' 'Fyodorova' 'Yobanna'
 'Boni' 'Monds' 'Okeke' 'Gilleland' 'Chiemela' 'Nkemakolam' 'Estrada'
 'Lombardi' 'Ubanwa' 'Black' 'Chimezie' 'Caffyn' 'Sheets' 'Buchi' 'Kable'
 'Pai' 'Chifley' 'Ibezimako' 'Genovesi' 'Gough' 'Zito' 'Trentino'
 'Ejimofor' 'Onwubiko' 'Mistry' 'Echezonachukwu' 'Chiemezie' 'Nnamdi'
 'Yudina' 'Rowntree' 'Kaeppel' 'Onwuka' 'Okwudiliolisa' 'Iqbal' 'Rene'
 'Houghton' 'Yefremova' 'Frewin' 'Mays' 'Chinwemma' 'Uvarov' 'Zuyeva'
 'Maccallum' 'Biryukov' 'De Luca' 'Johnstone' 'Fennell' 'Feng' 'Chikelu'
 'Atherton' 'Uchechukwu' 'Lombardo' 'Li Fonti' 'Trevisan' 'Udinesi'
 'Zuyev' 'Bage' 'Udinese' "O'Callaghan" 'Yudin' 'Kistler' 'Iheanacho'
 'Ngozichukwuka' 'Akobundu' 'Nucci' 'Chinwendu' 'Ndukaku' 'Li' 'Ruse'
 'Okwukwe' 'Burns' 'Chikezie' 'Ulyanov' 'Nkemakonam' 'Ponomarev'
 'Bancroft' 'Dike' 'Padovano' "O'Loughlin" 'Chukwueloka' 'Aksyonov'
 'Tretiakov' 'Ugoji' 'Yashina' 'Chifo' 'Omeokachie' "O'Toole"
 'De Bernales' 'Ukaegbunam' 'Gorman' 'McLean' 'Ugorji' 'Macintyre'
 'Frolova' 'Pye' 'Chibuzo' 'Narelle' 'Sholes' 'Ponomaryov' 'Udobata'
 'Macnamara' 'Onwuamaegbu' 'Zaytseva' 'Czajkowski' 'Kesteven' 'Krawczyk'
 'Brierly' 'Kaur' 'Koehler' 'Chiebuka' 'McWilliam' 'Olisanugo' 'Mollison'
 'Fink' 'Miah' 'Onwughara' 'Onochie' 'Gentry' 'Nwebube' 'Bess' 'Pritchard'
 'Ikedinachukwu' 'Nnanna' 'Babbage' 'Ejikemeifeuwa' 'Uchenna' 'Kuznetsova'
 'Pipes' 'Kincaid' 'Balsillie' 'Neumann' 'Hingston' 'Bair' 'Hickey'
 'Jamieson' 'Obijiaku' 'Chijioke' 'Endrizzi' 'Azikiwe' 'Zox' 'Okoli'
 'Palfreyman' 'Oluchukwu' 'Hightower' 'Molineux' 'Akabueze' 'Ponomaryova'
 'Soto' 'Kenechukwu' 'Onyemaechi' 'Davydova' 'Galkin' 'Whitelegge'
 'McClinton' 'Cawood' 'Nnaemeka' 'Kline' 'Oluchi' 'Shen' 'Huggins'
 'Pendergrass' "O'Loghlen" 'Loane' 'Maughan' 'Yefimov' 'Yegorov'
 'Nnabuife' 'Kolesnikov' 'Ekechukwu' 'Fennescey' 'Fyodorov' 'Nwokeocha'
 'McEwan' 'Smeaton' 'Ponce' 'Pino' 'Mello' 'Yegorova' 'Onwuatuegwu'
 'Yevdokimova' 'Onwuemelie' 'Hovell' 'Aksakova' 'Chineze' 'Davide'
 'Iweobiegbulam' "O'Meara" 'Okonkwo' 'Ibragimova' 'Lattimore' 'Efimov'
 'Chimaobim' 'Riddle' 'Tikhonov' 'Wright' "O'Kane" 'Sneddon' 'McFarland'
 'Bock' 'Kudryashova' 'Cawthorne' 'Yocum' 'Zhirov' 'Nwagugheuzo'
 'Cavenagh' 'Fetherstonhaugh' 'Paling' 'McElhone' 'Ma' 'Romano' 'Chukwuma'
 'Nebechi' 'Shipp' 'Loewenthal' 'Fadden' 'Miller' 'Yip' 'Nepean' 'Greco'
 'Ruggiero' 'Onyenachiya' 'Kolesnikova' 'Rubeo' 'Efremova' 'Obinna'
 'Hughes-Jones' 'Aksenova' 'Hargrave' 'Huddart' 'Chukwunonso' 'Macrossan'
 'Cawker' 'Fokina' 'Haugh' 'Dreyer' 'Henty' 'Davidson' 'Macgroarty'
 'Chung' 'Zikoranachukwudimma' 'Maitland' 'Mai' 'Tobeolisa' 'McElyea'
 'Bellucci' 'Boulger' 'Kumm' 'Thomson' 'Deleon' 'Rippey' 'Rounsevell'
 'Ives' 'Bell' 'Chukwuraenye' "O'Loghlin" 'Kornilova' 'Ibeamaka'
 'McWilliams' 'Brownlow' 'Mao' 'Shillito' 'Chiagoziem' 'Haddon'
 'Cumbrae-Stewart' 'Lueck' 'Koo' 'Rishel' 'Ross' 'Aparicio' 'Johnston'
 'MacPherson' 'Maconochie' 'Pape' 'Obielumani' 'Chieloka' 'Shipton'
 'Brownless' 'Padovesi' "B'eng" 'Lajoie' 'Sheppard' 'Bitter' 'Ni'
 'Yirawala' 'Liardet' 'Mironov' 'Farrar' 'Chidalu' 'McIntosh' "Ch'iang"
 'She' 'Aikenhead' 'Grosse' 'Longo' 'Titheradge' 'Cairns' 'Oster'
 'Azubuike' 'Whitehouse' 'Gidney' 'Curnow' 'Wei' 'Fokine' 'Kepley'
 'Cisneros' 'Sargood' 'Foveaux' 'Fries' 'Skelton' 'Gresswell' 'Wan'
 'Tisdall' 'Cocci' 'Kenechi' 'Gadsdon' 'Groom' 'Wang' 'Toth' 'Cribb'
 'Tretyakova' 'Tipton' 'Ibeabuchi' 'Sal' 'Bonham' 'Phelan' 'Fang' 'Hales'
 'Hirst' 'Mackay' 'Graham' 'Dann' 'Kennedy' 'Macfarlan' 'Illingworth'
 'Okorie' 'Sargent' 'K?an' 'Ewen' 'Zikoranaudodimma' 'Raff' 'Shand'
 'McNeil' "O'Connor" 'McKay' 'Lassetter' 'Chuter' 'Baddeley' 'Diggs'
 'Fisk' 'Bales' 'He' 'MacDonnell' 'Eremenko' 'Chiabuotu' 'Gadsden' 'Nott'
 'Zaitsev' 'Ifeatu' 'Dore' 'Fitts' 'Ochoa' 'Outhwaite' 'Ahern' "B'Crab"
 'Fane' 'H?an' 'Nweke' 'Kaleski' 'Liang' 'Linton' 'Macknight' 'Romani'
 'Fleming' 'Mairinger' 'Macartney' 'Luccino' 'Akhtar' 'Simpson' 'Mamelu'
 'Niehaus' 'Purdy' 'Linger' 'Ratten' 'Hayslett' 'Eipper' 'Akudinobi'
 'Pardey' 'Blesing' 'Otoole' 'Bevan' "L'ien" 'Burtch' 'Dettmann'
 'Trentini' 'Lappin' 'Bergamaschi' 'Lujan' 'Pacheco' 'Brazenor' 'Lupton'
 'Rios' 'Golubeva' 'Moseley' 'Harker' 'Hodge' 'Bovee' 'Chimaoke' 'McIver'
 'Hughes' 'Yewen' 'Tardent' 'Chiemeka' 'Luffman' 'Kegley' 'McEncroe'
 'Eiland' 'Erskine' 'Chikere' 'Fyans' 'Logue' 'Pethard' 'Neumayer' 'Fitch'
 'Gomes' 'Chao' 'Gannon' 'Nickson' 'Pardo' 'Doyne' 'Mault' 'Avent'
 'Lockington' 'McNeill' 'Chukwumelu' 'Fomina' 'Kibble' 'Dyson' 'Macchi'
 'John' 'Shanti' 'Hixson' 'Chubb' 'Krichauff' 'Shaver']


CreditScore :  [651. 639. 619. 543. 749. 678. 774. 696. 590. 663. 628. 676. 725. 773.
 564. 702. 730. 661. 608. 632. 627. 614. 579. 633. 634. 715. 682. 637.
 778. 645. 586. 684. 667. 554. 643. 850. 581. 577. 680. 583. 712. 745.
 727. 811. 624. 704. 652. 605. 722. 592. 689. 733. 584. 679. 746. 731.
 498. 544. 648. 675. 521. 673. 598. 687. 823. 550. 611. 603. 656. 738.
 466. 707. 642. 709. 585. 717. 558. 694. 681. 659. 822. 617. 454. 622.
 630. 591. 708. 641. 565. 615. 649. 818. 706. 486. 650. 596. 606. 545.
 588. 726. 580. 794. 562. 739. 669. 616. 686. 693. 828. 556. 599. 677.
 742. 683. 613. 623. 653. 691. 671. 501. 710. 535. 662. 567. 636. 516.
 542. 751. 537. 601. 705. 621. 812. 602. 761. 612. 724. 701. 582. 674.
 646. 721. 576. 758. 668. 594. 825. 492. 629. 604. 719. 741. 644. 569.
 665. 729. 779. 713. 703. 692. 647. 597. 711. 526. 593. 769. 685. 695.
 568. 757. 697. 595. 539. 744. 699. 587. 631. 714. 557. 607. 833. 771.
 688. 748. 698. 718. 625. 802. 785. 549. 732. 589. 640. 735. 750. 766.
 763. 765. 571. 508. 479. 578. 572. 547. 573. 775. 655. 439. 638. 795.
 829. 477. 759. 654. 474. 831. 806. 743. 660. 847. 561. 777. 814. 767.
 821. 762. 485. 635. 716. 753. 531. 488. 781. 836. 756. 787. 803. 658.
 796. 786. 835. 755. 523. 700. 752. 525. 848. 534. 553. 609. 481. 575.
 754. 813. 472. 824. 666. 538. 807. 473. 478. 841. 849. 790. 529. 797.
 496. 438. 798. 559. 747. 524. 657. 570. 690. 528. 555. 792. 437. 789.
 793. 815. 670. 551. 482. 837. 782. 574. 728. 664. 449. 770. 826. 810.
 846. 723. 791. 512. 819. 509. 600. 734. 768. 493. 487. 484. 494. 489.
 618. 495. 513. 510. 839. 468. 809. 467. 620. 843. 530. 507. 844. 459.
 431. 764. 788. 560. 540. 442. 610. 471. 720. 476. 838. 527. 805. 776.
 563. 626. 842. 801. 546. 772. 518. 834. 737. 740. 506. 490. 520. 505.
 497. 760. 548. 672. 515. 817. 736. 456. 491. 461. 832. 827. 483. 469.
 464. 499. 536. 511. 845. 830. 804. 503. 452. 816. 446. 434. 502.]


Geography :  ['France' 'Spain' 'Germany']


Gender :  ['Female' 'Male']


Age :  [33. 42. 34. 37. 47. 43. 48. 38. 49. 35. 39. 27. 40. 36. 41. 29. 30. 26.
 54. 53. 32. 28. 64. 56. 46. 50. 52. 31. 44. 67. 65. 24. 45. 59. 62. 57.
 66. 51. 55. 23. 25. 60. 68. 18. 22. 58. 70. 21. 71. 19. 63. 20. 61. 69.
 72. 74.]


Tenure :  [ 0.  9.  5.  7.  4.  3.  8.  2.  6.  1. 10.]


Balance :  [     0.   101470.29 104584.11 ...  81042.42 111071.36 121315.24]


NumOfProducts :  [2. 1. 3. 4.]


HasCrCard :  [1. 0.]


IsActiveMember :  [1. 0.]


EstimatedSalary :  [ 94499.06 152874.75  79919.13 ...  52441.15  59653.03 102549.11]

In [131]:
from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split


X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)


transform = ColumnTransformer(transformers=[
    ("encoder",OneHotEncoder(handle_unknown='ignore', sparse_output=False),X.select_dtypes(include=["object"]).columns),
    ("scaler",StandardScaler(),X.select_dtypes(include=["int64","float64"]).columns)
], remainder="passthrough")

pipeline=Pipeline([
    ("transform",transform),
    ("lr",LogisticRegression())
])

pipeline.fit(X_train,y_train)

Pipeline(steps=[('transform',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('encoder',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  Index(['Surname', 'Geography', 'Gender'], dtype='object')),
                                                 ('scaler', StandardScaler(),
                                                  Index(['id', 'CustomerId', 'CreditScore', 'Age', 'Tenure', 'Balance',
       'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary'],
      dtype='object'))])),
                ('lr', LogisticRegression())])

In [132]:
y_predict = pipeline.predict(X_test)
y_prob = pipeline.predict_proba(X_test)[:, 1]

In [133]:
from sklearn.metrics import classification_report, roc_auc_score


print("Classification Report:")
print(classification_report(y_test, y_predict))

auc = roc_auc_score(y_test, y_prob)
print(f"ROC-AUC Score: {auc:.4f}")

Classification Report:
              precision    recall  f1-score   support

         0.0       0.89      0.96      0.92      2402
         1.0       0.77      0.53      0.63       598

    accuracy                           0.88      3000
   macro avg       0.83      0.75      0.78      3000
weighted avg       0.87      0.88      0.87      3000

ROC-AUC Score: 0.8873

In [135]:
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, roc_auc_score, accuracy_score, recall_score
import pandas as pd


models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "Random Forest": RandomForestClassifier(random_state=42),
    "Gradient Boosting": GradientBoostingClassifier(random_state=42),
    "K-Nearest Neighbors": KNeighborsClassifier()
}


comparison_data = []


for model_name, model_obj in models.items():

    current_pipeline = Pipeline([
        ("transform", transform),
        ("clf", model_obj)
    ])
    
  
    current_pipeline.fit(X_train, y_train)
    

    preds = current_pipeline.predict(X_test)
    probs = current_pipeline.predict_proba(X_test)[:, 1]
    

    accuracy = accuracy_score(y_test, preds)
    recall_churn = recall_score(y_test, preds, pos_label=1) 
    auc_score = roc_auc_score(y_test, probs)
    

    comparison_data.append({
        "Model": model_name,
        "Accuracy": accuracy,
        "Recall (Churn)": recall_churn,
        "ROC-AUC": auc_score
    })


results_df = pd.DataFrame(comparison_data)
print("\nModel Comparison Table:")
print(results_df)

Model Comparison Table:
                 Model  Accuracy  Recall (Churn)   ROC-AUC
0  Logistic Regression  0.875000        0.530100  0.887306
1        Random Forest  0.887667        0.523411  0.922482
2    Gradient Boosting  0.895000        0.598662  0.937496
3  K-Nearest Neighbors  0.872667        0.541806  0.865277